import type { CategoryPreset, LanguagePreset, CountryPreset } from "./types";

export const FALLBACK_LOGO =
  "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='48' height='48' viewBox='0 0 24 24' fill='none' stroke='%238b5cf6' stroke-width='1.5'%3E%3Crect x='2' y='7' width='20' height='15' rx='2'%3E%3C/rect%3E%3Cpolyline points='17 2 12 7 7 2'%3E%3C/polyline%3E%3C/svg%3E";

export const DEFAULT_PLAYLIST = "https://iptv-org.github.io/iptv/index.category.m3u";

export const IPTV_ORG_CATEGORIES: CategoryPreset[] = [
  { name: "Animation", url: "https://iptv-org.github.io/iptv/categories/animation.m3u", count: 98 },
  { name: "Auto", url: "https://iptv-org.github.io/iptv/categories/auto.m3u", count: 25 },
  { name: "Business", url: "https://iptv-org.github.io/iptv/categories/business.m3u", count: 74 },
  { name: "Classic", url: "https://iptv-org.github.io/iptv/categories/classic.m3u", count: 68 },
  { name: "Comedy", url: "https://iptv-org.github.io/iptv/categories/comedy.m3u", count: 94 },
  { name: "Cooking", url: "https://iptv-org.github.io/iptv/categories/cooking.m3u", count: 42 },
  { name: "Culture", url: "https://iptv-org.github.io/iptv/categories/culture.m3u", count: 173 },
  { name: "Documentary", url: "https://iptv-org.github.io/iptv/categories/documentary.m3u", count: 193 },
  { name: "Education", url: "https://iptv-org.github.io/iptv/categories/education.m3u", count: 239 },
  { name: "Entertainment", url: "https://iptv-org.github.io/iptv/categories/entertainment.m3u", count: 676 },
  { name: "Family", url: "https://iptv-org.github.io/iptv/categories/family.m3u", count: 57 },
  { name: "General", url: "https://iptv-org.github.io/iptv/categories/general.m3u", count: 2496 },
  { name: "Kids", url: "https://iptv-org.github.io/iptv/categories/kids.m3u", count: 299 },
  { name: "Legislative", url: "https://iptv-org.github.io/iptv/categories/legislative.m3u", count: 182 },
  { name: "Lifestyle", url: "https://iptv-org.github.io/iptv/categories/lifestyle.m3u", count: 115 },
  { name: "Movies", url: "https://iptv-org.github.io/iptv/categories/movies.m3u", count: 608 },
  { name: "Music", url: "https://iptv-org.github.io/iptv/categories/music.m3u", count: 697 },
  { name: "News", url: "https://iptv-org.github.io/iptv/categories/news.m3u", count: 967 },
  { name: "Outdoor", url: "https://iptv-org.github.io/iptv/categories/outdoor.m3u", count: 62 },
  { name: "Religious", url: "https://iptv-org.github.io/iptv/categories/religious.m3u", count: 735 },
  { name: "Science", url: "https://iptv-org.github.io/iptv/categories/science.m3u", count: 20 },
  { name: "Series", url: "https://iptv-org.github.io/iptv/categories/series.m3u", count: 362 },
  { name: "Sports", url: "https://iptv-org.github.io/iptv/categories/sports.m3u", count: 412 },
  { name: "Travel", url: "https://iptv-org.github.io/iptv/categories/travel.m3u", count: 46 },
  { name: "Weather", url: "https://iptv-org.github.io/iptv/categories/weather.m3u", count: 16 },
  { name: "Undefined", url: "https://iptv-org.github.io/iptv/categories/undefined.m3u", count: 4023 },
];

export const IPTV_ORG_LANGUAGES: LanguagePreset[] = [
  { name: "English", url: "https://iptv-org.github.io/iptv/languages/eng.m3u" },
  { name: "Spanish", url: "https://iptv-org.github.io/iptv/languages/spa.m3u" },
  { name: "French", url: "https://iptv-org.github.io/iptv/languages/fra.m3u" },
  { name: "Arabic", url: "https://iptv-org.github.io/iptv/languages/ara.m3u" },
  { name: "Portuguese", url: "https://iptv-org.github.io/iptv/languages/por.m3u" },
  { name: "German", url: "https://iptv-org.github.io/iptv/languages/deu.m3u" },
  { name: "Russian", url: "https://iptv-org.github.io/iptv/languages/rus.m3u" },
  { name: "Chinese", url: "https://iptv-org.github.io/iptv/languages/zho.m3u" },
  { name: "Hindi", url: "https://iptv-org.github.io/iptv/languages/hin.m3u" },
  { name: "Turkish", url: "https://iptv-org.github.io/iptv/languages/tur.m3u" },
  { name: "Italian", url: "https://iptv-org.github.io/iptv/languages/ita.m3u" },
  { name: "Bengali", url: "https://iptv-org.github.io/iptv/languages/ben.m3u" },
  { name: "Dutch", url: "https://iptv-org.github.io/iptv/languages/nld.m3u" },
  { name: "Japanese", url: "https://iptv-org.github.io/iptv/languages/jpn.m3u" },
  { name: "Korean", url: "https://iptv-org.github.io/iptv/languages/kor.m3u" },
  { name: "Persian", url: "https://iptv-org.github.io/iptv/languages/fas.m3u" },
  { name: "Polish", url: "https://iptv-org.github.io/iptv/languages/pol.m3u" },
  { name: "Greek", url: "https://iptv-org.github.io/iptv/languages/ell.m3u" },
  { name: "Swedish", url: "https://iptv-org.github.io/iptv/languages/swe.m3u" },
  { name: "Ukrainian", url: "https://iptv-org.github.io/iptv/languages/ukr.m3u" },
  { name: "Vietnamese", url: "https://iptv-org.github.io/iptv/languages/vie.m3u" },
  { name: "Thai", url: "https://iptv-org.github.io/iptv/languages/tha.m3u" },
  { name: "Urdu", url: "https://iptv-org.github.io/iptv/languages/urd.m3u" },
  { name: "Albanian", url: "https://iptv-org.github.io/iptv/languages/sqi.m3u" },
];

export const IPTV_ORG_COUNTRIES: CountryPreset[] = [
  { name: "United States", code: "us", url: "https://iptv-org.github.io/iptv/countries/us.m3u" },
  { name: "United Kingdom", code: "gb", url: "https://iptv-org.github.io/iptv/countries/gb.m3u" },
  { name: "India", code: "in", url: "https://iptv-org.github.io/iptv/countries/in.m3u" },
  { name: "Germany", code: "de", url: "https://iptv-org.github.io/iptv/countries/de.m3u" },
  { name: "France", code: "fr", url: "https://iptv-org.github.io/iptv/countries/fr.m3u" },
  { name: "Russia", code: "ru", url: "https://iptv-org.github.io/iptv/countries/ru.m3u" },
  { name: "Italy", code: "it", url: "https://iptv-org.github.io/iptv/countries/it.m3u" },
  { name: "Spain", code: "es", url: "https://iptv-org.github.io/iptv/countries/es.m3u" },
  { name: "Brazil", code: "br", url: "https://iptv-org.github.io/iptv/countries/br.m3u" },
  { name: "Canada", code: "ca", url: "https://iptv-org.github.io/iptv/countries/ca.m3u" },
  { name: "Australia", code: "au", url: "https://iptv-org.github.io/iptv/countries/au.m3u" },
  { name: "Netherlands", code: "nl", url: "https://iptv-org.github.io/iptv/countries/nl.m3u" },
  { name: "Turkey", code: "tr", url: "https://iptv-org.github.io/iptv/countries/tr.m3u" },
  { name: "Saudi Arabia", code: "sa", url: "https://iptv-org.github.io/iptv/countries/sa.m3u" },
  { name: "Mexico", code: "mx", url: "https://iptv-org.github.io/iptv/countries/mx.m3u" },
  { name: "Poland", code: "pl", url: "https://iptv-org.github.io/iptv/countries/pl.m3u" },
  { name: "China", code: "cn", url: "https://iptv-org.github.io/iptv/countries/cn.m3u" },
  { name: "Japan", code: "jp", url: "https://iptv-org.github.io/iptv/countries/jp.m3u" },
  { name: "South Korea", code: "kr", url: "https://iptv-org.github.io/iptv/countries/kr.m3u" },
  { name: "Indonesia", code: "id", url: "https://iptv-org.github.io/iptv/countries/id.m3u" },
  { name: "Pakistan", code: "pk", url: "https://iptv-org.github.io/iptv/countries/pk.m3u" },
  { name: "Bangladesh", code: "bd", url: "https://iptv-org.github.io/iptv/countries/bd.m3u" },
  { name: "Nigeria", code: "ng", url: "https://iptv-org.github.io/iptv/countries/ng.m3u" },
  { name: "Egypt", code: "eg", url: "https://iptv-org.github.io/iptv/countries/eg.m3u" },
  { name: "Ukraine", code: "ua", url: "https://iptv-org.github.io/iptv/countries/ua.m3u" },
  { name: "Argentina", code: "ar", url: "https://iptv-org.github.io/iptv/countries/ar.m3u" },
  { name: "Greece", code: "gr", url: "https://iptv-org.github.io/iptv/countries/gr.m3u" },
  { name: "Vietnam", code: "vn", url: "https://iptv-org.github.io/iptv/countries/vn.m3u" },
  { name: "Thailand", code: "th", url: "https://iptv-org.github.io/iptv/countries/th.m3u" },
  { name: "Iran", code: "ir", url: "https://iptv-org.github.io/iptv/countries/ir.m3u" },
];
